### ISSUE TITLE
Torchvision Version

### ISSUE THREAD

**Issue by aminul-huq** [UsamaI000/CamVid-Segmentation-Pytorch#1]
Hi @UsamaI000 , which version of torchvision are you using for this project? In Camvid.py in line 32 you used PILToTensor(). I was not able to use it. Can you tell me the version of your torchvision please?

**Comment by UsamaI000** [comment]
> Hi @UsamaI000 , which version of torchvision are you using for this project? In Camvid.py in line 32 you used PILToTensor(). I was not able to use it. Can you tell me the version of your torchvision please?

Hi @aminul-huq, I am using Trochvision version "0.7.0+cu101".  I usually work on colab so this is the version that is available on it.
