### ISSUE TITLE
mask pre processing

### ISSUE THREAD

**Issue by soans1994** [UsamaI000/CamVid-Segmentation-Pytorch#2]
hello author,

i have some query regarding semantic segmentation. i cannot use categorical cross entropy loss. I have coded the rgbmask to index and  my mask/ target dimension is (batch, numclasses, h, w) for 12 classes. I can use mse loss. when i try using categorical cross entropy it throws error as below.
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [16, 12, 256, 256]

**Comment by UsamaI000** [comment]
Categorical CE works on 3D matrice yours is of 4
